                                
                                    

                                  
                            

                      
                        
                    
                       
                   
                    
                   
                           
                         

                                    
                                    
                            
                                  
                                    

                                        
                                        

                             
                             
                             
                             
                             
                             
                             
                             
                             
                             
                              
                              
                              
                              
                              
                              
                                                          

                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                              
                               
                               
                                                              


// Static styles
                              
                              
                              
                              
                              
                              
                              
                              
                              

                              
                           
                            
                            
                            
                            
                            
                            
                             
                             
                             
                             
                             

                               
                               
                                   

                                                  

// Slider styles
                               
                           
                               

                              

// Listbox styles
                              
                              

                                                                         


                                                        
                                                               
                                                            
                                                                   
                                
                                                                                       

                                         
                                        
                                        
                                               
                                              
                                               
                                                                                                                                                                                                                                                          
                                    
                                      
                         

                                                                                                                                                                                          
                                     

                                                                  

                                                
                                                  
                                                   
                                                 

class ZTitle: ZUI_Static
{
	background[] = { "(profilenamespace getvariable ['GUI_BCG_RGB_R',0.13])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.54])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.21])", "(profilenamespace getvariable ['GUI_BCG_RGB_A',0.8])" };
	font = "PuristaLight";
	textSize = (((((safezoneW / safezoneH) min 1.2)/ 1.2)/ 25) * 1);
	height = 0.05;
	heightType = "absolute";
}
